sudo: required

# ubuntu 20.04
dist: focal

language: minimal

services:
  - docker

cache:
  directories:
    - builder/osxcross
    - target

before_script:
  - make download-osxcross
  - make build-task
  - make cargo-fmt-check
  - make cargo-clippy

script:
  - |
    set -e
    make cargo-test
    make assemble target=x86_64-unknown-linux-musl
    make assemble target=armv7-unknown-linux-musleabihf
    make assemble target=x86_64-apple-darwin
