sudo: required

language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - ./scripts.travis/setup_docker.sh
  # - ./scripts.travis/setup_docker.sh

before_script:
  - ./scripts/run_builder.sh cargo-fmt.sh --all-check

script:
  - |
    ./scripts/run_tests.sh &&
    ./scripts/build.sh
