sudo: required

# ubuntu 20.04
dist: focal

language: minimal

services:
  - docker

cache:
  directories:
    - builder/osxcross
    - target

before_script:
  - make download-osxcross
  - make build-task
  - make cargo-fmt-check
  - make cargo-clippy

script:
  - |
    set -e
    make cargo-test
    make assemble target=linux_x86
    make assemble target=linux_armv7
    make assemble target=macos_x86
