sudo: required

# ubuntu 20.04
dist: focal

language: minimal

services:
  - docker

before_script:
  - make cargo-fmt-check
  - make cargo-clippy
  - make download-osxcross

script:
  - |
    set -e
    make cargo-test
    make assemble target=linux_x86
    make assemble target=linux_armv7
    make assemble target=macos_x86
