sudo: required

dist: focal
language: minimal

services:
  - docker

cache:
  directories:
    - docker_images

before_install:
  - docker load -i docker_images/images.tar || true

before_cache:
  - docker save -o docker_images/images.tar $(docker images -a -q)

before_script:
  - ./scripts/run_builder.sh cargo-fmt.sh --all-check

script:
  - |
    ./scripts/run_tests.sh &&
    ./scripts/build.sh
