sudo: required

# ubuntu 20.04
dist: focal

language: minimal

services:
  - docker

before_script:
  - make cargo-fmt-check
  - make cargo-clippy

script:
  - |
    make cargo-test &&
    make assemble
