[package]
name = "wsb-pilot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
env-extractor = { path = "../../libs/env-extractor" }
lazy_static = "1.4"

[dependencies]
failure = "0.1"
