name: assemble
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: |
          sudo ./builder/apt-get.sh
      - run: |
          ./builder/init.sh
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
      - run: |
          ./builder/cargo-test.sh --debug --opt-level=0
        env:
          WSB_WORKSPACE: ${{ github.workspace }}

  target-linux-x86:
    needs: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}

      - name: Assemble artifacts
        run: |
          ./builder/assemble.sh
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
