name: assemble
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
#          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          key: ${{ runner.os }}-cargo-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: |
          sudo ./builder/apt-get.sh
      - run: |
          ./builder/init.sh
          ./builder/init.linux_x86.sh
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
          PLUS_PROJECT_ROOT: ${{ github.workspace }}
      - run: |
          ./builder/cargo-test.sh --debug --opt-level=0
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
          PLUS_PROJECT_ROOT: ${{ github.workspace }}

  target-linux-x86:
    needs: cargo-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
#          key: ${{ runner.os }}-cargo-musl-${{ hashFiles('**/Cargo.lock') }}
          key: ${{ runner.os }}-cargo-musl-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-musl-
      - run: |
          sudo ./builder/apt-get.sh
      - run: |
          ./builder/init.linux_x86.sh
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
          PLUS_PROJECT_ROOT: ${{ github.workspace }}

      - name: Assemble artifacts
        run: |
          ./builder/assemble.sh
        env:
          WSB_WORKSPACE: ${{ github.workspace }}
          PLUS_PROJECT_ROOT: ${{ github.workspace }}
